name: webengage_flutter
description: WebEngage Flutter plugin.
version: 1.4.1
homepage: https://webengage.com/
repository: https://github.com/WebEngage/webengage-flutter

environment:
  sdk: ">2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.webengage.webengage_plugin
        pluginClass: WebEngagePlugin
      ios:
        pluginClass: WebEngagePlugin
